config/routes.rb
Rails.application.routes.draw do
  # Non i18n routes. Alphabetically sorted.
  get '/api/health' => 'health/health#index'
  get '/api/health/database' => 'health/database#index'
  get '/api/health/jobs' => 'health/jobs#index'
  get '/api/openid_connect/certs' => 'openid_connect/certs#index'
  post '/api/openid_connect/token' => 'openid_connect/token#create'
  match '/api/openid_connect/token' => 'openid_connect/token#options', via: :options
  get '/api/openid_connect/userinfo' => 'openid_connect/user_info#show'
  post '/analytics' => 'analytics#create'

  # SAML secret rotation paths
  SamlEndpoint.suffixes.each do |suffix|
    get "/api/saml/metadata#{suffix}" => 'saml_idp#metadata', format: false
    match "/api/saml/logout#{suffix}" => 'saml_idp#logout', via: %i[get post delete]
    match "/api/saml/auth#{suffix}" => 'saml_idp#auth', via: %i[get post]
  end

  # Twilio Request URL for inbound SMS
  post '/api/sms/receive' => 'sms#receive'

  post '/api/service_provider' => 'service_provider#update'
  match '/api/voice/otp' => 'voice/otp#show',
        via: %i[get post],
        as: :voice_otp,
        defaults: { format: :xml }
  match '/api/twilio/voice' => 'twilio_voice#show',
        via: %i[get post],
        format: :xml

  get '/openid_connect/authorize' => 'openid_connect/authorization#index'
  get '/openid_connect/logout' => 'openid_connect/logout#index'

  # Routes that are triggered by lambda functions to initiate recurring jobs
  scope module: :recurring_job do
    post '/api/account_reset/send_notifications' => 'send_account_reset_notifications#create'
    post '/api/expired_letters' => 'expired_letters#create'
    post '/api/usps_download' => 'undeliverable_address#create'
    post '/api/usps_upload' => 'usps_upload#create'
  end

  # i18n routes. Alphabetically sorted.
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    # Devise handles login itself. It's first in the chain to avoid a redirect loop during
    # authentication failure.
    # devise_for(
    #   :users,
    #   skip: %i[confirmations sessions registrations two_factor_authentication],
    #   controllers: { passwords: 'users/reset_passwords' },
    # )

    # Additional device controller routes.
    devise_for(
      :users,
      skip: %i[confirmations sessions registrations two_factor_authentication passwords],
    )

    devise_scope :user do
      get '/users/password/new' => 'users/reset_passwords#new', as: :new_user_password
      get '/users/password/edit' => 'users/reset_passwords#edit', as: :edit_user_password
      patch '/users/password' => 'users/reset_passwords#update', as: :user_password
      put '/users/password' => 'users/reset_passwords#update', as: nil
      post '/users/password' => 'users/reset_passwords#create', as: nil

      get '/' => 'users/sessions#new', as: :new_user_session
      post '/' => 'users/sessions#create', as: :user_session
      get '/logout' => 'users/sessions#destroy', as: :destroy_user_session
      get '/active' => 'users/sessions#active'

      if FeatureManagement.allow_piv_cac_login?
        get '/login/piv_cac' => 'users/piv_cac_login#new'
        get '/login/present_piv_cac' => 'users/piv_cac_login#redirect_to_piv_cac_service'
        get '/login/password' => 'password_capture#new', as: :capture_password
        post '/login/password' => 'password_capture#create'
      end

      get '/account_reset/request' => 'account_reset/request#show'
      post '/account_reset/request' => 'account_reset/request#create'
      unless FeatureManagement.disallow_ial2_recovery?
        get '/account_reset/recover' => 'account_reset/recover#show'
        post '/account_reset/recover' => 'account_reset/recover#create'
        get '/account_reset/recover/email_sent' => 'account_reset/recover#email_sent'
      end
      get '/account_reset/cancel' => 'account_reset/cancel#show'
      post '/account_reset/cancel' => 'account_reset/cancel#create'
      get '/account_reset/confirm_request' => 'account_reset/confirm_request#show'
      get '/account_reset/delete_account' => 'account_reset/delete_account#show'
      delete '/account_reset/delete_account' => 'account_reset/delete_account#delete'
      get '/account_reset/confirm_delete_account' => 'account_reset/confirm_delete_account#show'

      get '/login/two_factor/options' => 'two_factor_authentication/options#index'
      post '/login/two_factor/options' => 'two_factor_authentication/options#create'

      get '/login/two_factor/authenticator' => 'two_factor_authentication/totp_verification#show'
      post '/login/two_factor/authenticator' => 'two_factor_authentication/totp_verification#create'
      get '/login/two_factor/personal_key' => 'two_factor_authentication/personal_key_verification#show'
      post '/login/two_factor/personal_key' => 'two_factor_authentication/personal_key_verification#create'
      get '/login/two_factor/piv_cac' => 'two_factor_authentication/piv_cac_verification#show'
      get '/login/two_factor/webauthn' => 'two_factor_authentication/webauthn_verification#show'
      patch '/login/two_factor/webauthn' => 'two_factor_authentication/webauthn_verification#confirm'
      get 'login/two_factor/backup_code' => 'two_factor_authentication/backup_code_verification#show'
      post 'login/two_factor/backup_code' => 'two_factor_authentication/backup_code_verification#create'
      get  '/login/two_factor/:otp_delivery_preference' => 'two_factor_authentication/otp_verification#show',
           as: :login_two_factor, constraints: { otp_delivery_preference: /sms|voice/ }
      post '/login/two_factor/:otp_delivery_preference' => 'two_factor_authentication/otp_verification#create',
           as: :login_otp

      get '/reauthn' => 'mfa_confirmation#new', as: :user_password_confirm
      post '/reauthn' => 'mfa_confirmation#create', as: :reauthn_user_password
      get '/timeout' => 'users/sessions#timeout'
    end

    if Figaro.env.enable_test_routes == 'true'
      namespace :test do
        # Assertion granting test start + return.
        get '/saml' => 'saml_test#start'
        get '/saml/decode_assertion' => 'saml_test#start'
        post '/saml/decode_assertion' => 'saml_test#decode_response'
        post '/saml/decode_slo_request' => 'saml_test#decode_slo_request'
        get '/piv_cac_entry' => 'piv_cac_authentication_test_subject#new'
        post '/piv_cac_entry' => 'piv_cac_authentication_test_subject#create'
      end
    end

    # Non-devise-controller routes. Alphabetically sorted.
    get '/.well-known/openid-configuration' => 'openid_connect/configuration#index',
        as: :openid_connect_configuration

    get '/account' => 'accounts#show'
    get '/account/devices/:id/events' => 'events#show', as: :account_events
    get '/account/delete' => 'users/delete#show', as: :account_delete
    delete '/account/delete' => 'users/delete#delete'
    get '/account/reactivate/start' => 'reactivate_account#index', as: :reactivate_account
    put '/account/reactivate/start' => 'reactivate_account#update'
    get '/account/reactivate/verify_password' => 'users/verify_password#new', as: :verify_password
    put '/account/reactivate/verify_password' => 'users/verify_password#update', as: :update_verify_password
    get '/account/reactivate/verify_personal_key' => 'users/verify_personal_key#new',
        as: :verify_personal_key
    post '/account/reactivate/verify_personal_key' => 'users/verify_personal_key#create',
         as: :create_verify_personal_key

    get '/events/disavow' => 'event_disavowal#new', as: :event_disavowal
    post '/events/disavow' => 'event_disavowal#create', as: :events_disavowal

    get '/piv_cac' => 'users/piv_cac_authentication_setup#new', as: :setup_piv_cac
    delete '/piv_cac' => 'users/piv_cac_authentication_setup#delete', as: :disable_piv_cac
    get '/present_piv_cac' => 'users/piv_cac_authentication_setup#redirect_to_piv_cac_service', as: :redirect_to_piv_cac_service

    get '/webauthn_setup' => 'users/webauthn_setup#new', as: :webauthn_setup
    patch '/webauthn_setup' => 'users/webauthn_setup#confirm'
    delete '/webauthn_setup' => 'users/webauthn_setup#delete'
    get '/webauthn_setup_delete' => 'users/webauthn_setup#show_delete'

    delete '/authenticator_setup' => 'users/totp_setup#disable', as: :disable_totp
    get '/authenticator_setup' => 'users/totp_setup#new'
    patch '/authenticator_setup' => 'users/totp_setup#confirm'
    get '/authenticator_start' => 'users/totp_setup#start'

    get '/recovery_key_setup' => 'users/recovery_key_setup#new'
    patch '/recovery_key_setup' => 'users/recovery_key_setup#confirm'

    get '/forgot_password' => 'forgot_password#show'

    get '/manage/password' => 'users/passwords#edit'
    patch '/manage/password' => 'users/passwords#update'

    get '/add/email' => 'users/emails#show'
    post '/add/email' => 'users/emails#add'
    get '/add/email/confirm' => 'users/email_confirmations#create', as: :add_email_confirmation
    get '/add/email/verify_email' => 'users/emails#verify', as: :add_email_verify_email
    post '/add/email/resend' => 'users/emails#resend'

    delete '/manage/email/:id' => 'users/emails#delete', as: :delete_email
    get '/manage/email/confirm_delete/:id' => 'users/emails#confirm_delete',
        as: :manage_email_confirm_delete

    get '/add/phone' => 'users/phones#add'
    post '/add/phone' => 'users/phones#create'
    get '/manage/phone' => 'users/phones#edit'
    match '/manage/phone' => 'users/phones#update', via: %i[patch put]
    delete '/manage/phone' => 'users/phones#delete'
    get '/manage/personal_key' => 'users/personal_keys#show', as: :manage_personal_key
    post '/account/personal_key' => 'users/personal_keys#create', as: :create_new_personal_key
    post '/manage/personal_key' => 'users/personal_keys#update'

    get '/otp/send' => 'users/two_factor_authentication#send_code'
    get '/two_factor_options' => 'users/two_factor_authentication_setup#index'

app/controllers/concerns/idv/phone_otp_rate_limitable.rb
module Idv
  module PhoneOtpRateLimitable
    extend ActiveSupport::Concern

    included do
      before_action :confirm_two_factor_authenticated
      before_action :handle_locked_out_user
    end

    def handle_locked_out_user
      reset_attempt_count_if_user_no_longer_locked_out
      return unless decorated_user.locked_out?
      analytics.track_event(Analytics::IDV_PHONE_CONFIRMATION_OTP_RATE_LIMIT_LOCKED_OUT)
      handle_too_many_otp_attempts
      false
    end

    def reset_attempt_count_if_user_no_longer_locked_out
      return unless decorated_user.no_longer_locked_out?

      UpdateUser.new(
        user: current_user,
        attributes: {
          second_factor_attempts_count: 0,
          second_factor_locked_at: nil,
        },
      ).call
    end

    def handle_too_many_otp_sends
      analytics.track_event(Analytics::IDV_PHONE_CONFIRMATION_OTP_RATE_LIMIT_SENDS)
      handle_max_attempts('otp_requests')
    end

    def handle_too_many_otp_attempts
      analytics.track_event(Analytics::IDV_PHONE_CONFIRMATION_OTP_RATE_LIMIT_ATTEMPTS)
      handle_max_attempts('otp_login_attempts')
    end

    def handle_max_attempts(type)
      presenter = TwoFactorAuthCode::MaxAttemptsReachedPresenter.new(
        type,
        decorated_user,
      )
      sign_out
      render_full_width('shared/_failure', locals: { presenter: presenter })
    end

    def decorated_user
      current_user.decorate
    end
  end
end

app/controllers/concerns/idv/phone_otp_sendable.rb
module Idv
  module PhoneOtpSendable
    extend ActiveSupport::Concern

    included do
      before_action :confirm_two_factor_authenticated
      before_action :handle_locked_out_user
    end

    def send_phone_confirmation_otp
      send_phone_confirmation_otp_service.call
    end

    def send_phone_confirmation_otp_rate_limited?
      send_phone_confirmation_otp_service.user_locked_out?
    end

    def invalid_phone_number(telephony_error)
      capture_analytics_for_telephony_error(telephony_error)
      flash[:error] = telephony_error.friendly_message
      redirect_to idv_phone_url
    end

    private

    def send_phone_confirmation_otp_service
      @send_phone_confirmation_otp_service ||= Idv::SendPhoneConfirmationOtp.new(
        user: current_user,
        idv_session: idv_session,
      )
    end

    def capture_analytics_for_telephony_error(telephony_error)
      attributes = {
        error: telephony_error.class.to_s,
        message: telephony_error.message,
        context: 'idv',
        country: Phonelib.parse(send_phone_confirmation_otp_service.phone).country,
      }
      analytics.track_event(Analytics::TWILIO_PHONE_VALIDATION_FAILED, attributes)
    end
  end
end

app/controllers/idv/address_controller.rb
module Idv
  class AddressController < ApplicationController
    include IdvSession
    include IdvFailureConcern

    before_action :confirm_two_factor_authenticated

    def new
      analytics.track_event(Analytics::IDV_ADDRESS_VISIT)
    end

    def update
      form_result = idv_form.submit(profile_params)
      analytics.track_event(Analytics::IDV_ADDRESS_SUBMITTED, form_result.to_h)
      if form_result.success?
        success
      else
        failure
      end
    end

    private

    def idv_form
      Idv::AddressForm.new(
        user: current_user,
        previous_params: idv_session.previous_profile_step_params,
      )
    end

    def success
      profile_params.each do |key, value|
        user_session['idv/doc_auth']['pii_from_doc'][key] = value
      end
      redirect_to idv_doc_auth_url
    end

    def failure
      redirect_to idv_address_url
    end

    def profile_params
      params.require(:idv_form).permit(Idv::AddressForm::ATTRIBUTES)
    end
  end
end

app/controllers/idv/cac_controller.rb
module Idv
  class CacController < ApplicationController
    before_action :render_404_if_disabled
    before_action :confirm_two_factor_authenticated
    before_action :cac_callback

    include Flow::FlowStateMachine

    FSM_SETTINGS = {
      step_url: :idv_cac_step_url,
      final_url: :idv_review_url,
      flow: Idv::Flows::CacFlow,
      analytics_id: Analytics::CAC_PROOFING,
    }.freeze

    def render_404_if_disabled
      render_not_found unless Figaro.env.cac_proofing_enabled == 'true'
    end

    def cac_callback
      return unless request.path == idv_cac_step_path(:present_cac) && params[:token]
      user_session['idv/cac']['Idv::Steps::Cac::PresentCacStep'] = true
      redirect_to idv_cac_step_path(:enter_info)
    end
  end
end

app/controllers/idv/cancellations_controller.rb
module Idv
  class CancellationsController < ApplicationController
    include IdvSession

    before_action :confirm_two_factor_authenticated
    before_action :confirm_idv_needed

    def new
      properties = ParseControllerFromReferer.new(request.referer).call
      analytics.track_event(Analytics::IDV_CANCELLATION, properties)
      @presenter = CancellationPresenter.new(view_context: view_context)
    end

    def destroy
      analytics.track_event(Analytics::IDV_CANCELLATION_CONFIRMED)
      @presenter = CancellationConfirmationPresenter.new
      idv_session = user_session[:idv]
      idv_session&.clear
      reset_doc_auth
    end

    private

    def reset_doc_auth
      user_session.delete('idv/doc_auth')
      user_session['idv'] = { params: {}, step_attempts: { phone: 0 } }
    end
  end
end

app/controllers/idv/capture_doc_controller.rb
module Idv
  class CaptureDocController < ApplicationController
    include Flow::FlowStateMachine
    before_action :ensure_user_id_in_session

    FSM_SETTINGS = {
      step_url: :idv_capture_doc_step_url,
      final_url: :root_url,
      flow: Idv::Flows::CaptureDocFlow,
      analytics_id: Analytics::CAPTURE_DOC,
    }.freeze

    private

    def ensure_user_id_in_session
      return if session[:doc_capture_user_id]
      result = CaptureDoc::ValidateRequestToken.new(token).call
      analytics.track_event(FSM_SETTINGS[:analytics_id], result.to_h)
      process_result(result)
    end

    def process_result(result)
      if result.success?
        session[:doc_capture_user_id] = result.extra[:for_user_id]
      else
        flash[:error] = t('errors.capture_doc.invalid_link')
        redirect_to root_url
      end
    end

    def token
      params[:token]
    end
  end
end

app/controllers/idv/come_back_later_controller.rb
module Idv
  class ComeBackLaterController < ApplicationController
    before_action :confirm_two_factor_authenticated
    before_action :confirm_user_needs_usps_confirmation

    def show
      analytics.track_event(Analytics::IDV_COME_BACK_LATER_VISIT)
    end

    private

    def confirm_user_needs_usps_confirmation
      redirect_to account_url unless current_user.decorate.pending_profile_requires_verification?
    end
  end
end

app/controllers/idv/doc_auth_controller.rb
module Idv
  class DocAuthController < ApplicationController
    before_action :confirm_two_factor_authenticated
    before_action :redirect_if_mail_bounced
    before_action :redirect_if_pending_profile

    include IdvSession # remove if we retire the non docauth LOA3 flow
    include Flow::FlowStateMachine

    FSM_SETTINGS = {
      step_url: :idv_doc_auth_step_url,
      final_url: :idv_review_url,
      flow: Idv::Flows::DocAuthFlow,
      analytics_id: Analytics::DOC_AUTH,
    }.freeze

    def redirect_if_mail_bounced
      redirect_to idv_usps_url if current_user.decorate.usps_mail_bounced?
    end

    def redirect_if_pending_profile
      redirect_to verify_account_url if current_user.decorate.pending_profile_requires_verification?
    end
  end
end

app/views/idv/cac/_start_over_or_cancel.html.slim
br
= button_to(t('doc_auth.buttons.start_over'), idv_cac_step_path(:reset), method: :put,
        class: 'btn btn-link', form_class: 'inline-block')
= render 'shared/cancel', link: idv_cancel_path

app/views/idv/cac/enter_info.html.erb
<h5 class="my1 caps bold accent-blue"><%= t('cac_proofing.step', step: 2) %></h5>
<h1 class="h3 my0"><%= t('cac_proofing.headings.enter_info') %></h1>

<%= simple_form_for(:cac, url: url_for, method: 'PUT',
                    html: { autocomplete: 'off', method: :put, role: 'form' }) do |f| %>
  <fieldset class="ml0 p0 border-none">
    <div class="clearfix mxn1">
      <div class="sm-col sm-col-6 px1">
        <div class="mb3 tel required profile_dob">
          <label class="bold tel required" for="profile_dob"><abbr title="required" class="red display-none">*</abbr>
            <%= t('in_person_proofing.forms.dob') %>
          </label>
          <div id="dob-instructs" class="italic mb1">example: 01/17/1964</div>
          <input class="block col-12 field string tel required dob" aria-describedby="dob-instructs" required="required" aria-required="true" pattern="(0[1-9]|1[012])/(0[1-9]|1[0-9]|2[0-9]|3[01])/[0-9]{4}" type="tel" name="doc_auth[dob]" id="profile_dob"/>
        </div>
      </div>
    </div>
    <div class="clearfix mxn1">
      <div class="sm-col sm-col-6 px1">
        <div class="mb3 tel required profile_ssn">
          <label class="bold tel required" for="profile_ssn"><abbr title="required" class="red display-none">*</abbr>
            <%= t('in_person_proofing.forms.ssn') %>
          </label>
          <input class="block col-12 field string tel required ssn" required="required" aria-required="true" pattern="^\d{3}-?\d{2}-?\d{4}$" type="tel" name="doc_auth[ssn]" id="profile_ssn"/>
        </div>
      </div>
    </div>
  </fieldset>
  <fieldset class="m0 p0 border-none">
    <div class="mb3 string required profile_address1 mb1">
      <label class="bold string required" for="profile_address1"><abbr title="required" class="red display-none">*</abbr>
        <%= t('in_person_proofing.forms.address1') %>
      </label>
      <input class="block col-12 field string required" required="required" aria-required="true" maxlength="255" size="255" type="text" name="doc_auth[address1]" id="profile_address1"/>
    </div>
    <div class="mb3 string optional profile_address2">
      <label class="bold string optional" for="profile_address2">
        <%= t('in_person_proofing.forms.address2') %>
      </label>
      <input class="block col-12 field string optional" maxlength="255" size="255" type="text" name="doc_auth[address2]" id="profile_address2"/>
    </div>
    <div class="mb3 string required profile_city">
      <label class="bold string required" for="profile_city"><abbr title="required" class="red display-none">*</abbr>
        <%= t('in_person_proofing.forms.city') %>
      </label>
      <input class="block col-12 field string required" required="required" aria-required="true" maxlength="255" size="255" type="text" name="doc_auth[city]" id="profile_city"/>
    </div>
    <div class="clearfix mxn1">
      <div class="sm-col sm-col-8 px1">
        <div class="mb3 select required profile_state">
          <label class="bold select required" for="profile_state"><abbr title="required" class="red display-none">*</abbr>
            <%= t('in_person_proofing.forms.state') %>
          </label>
          <select class="block col-12 field select required" required="required" aria-required="true" name="doc_auth[state]" id="profile_state">
          <option value="AL">Alabama</option>
          <option value="AK">Alaska</option>
          <option value="AS">American Samoa</option>
          <option value="AZ">Arizona</option>
          <option value="AR">Arkansas</option>
          <option value="AA">Armed Forces Americas</option>
          <option value="AE">Armed Forces Others</option>
          <option value="AP">Armed Forces Pacific</option>
          <option value="CA">California</option>
          <option value="CO">Colorado</option>
          <option value="CT">Connecticut</option>
          <option value="DE">Delaware</option>
          <option selected="selected" value="DC">District of Columbia</option>
          <option value="FL">Florida</option>
          <option value="GA">Georgia</option>
          <option value="GU">Guam</option>
          <option value="HI">Hawaii</option>
          <option value="ID">Idaho</option>
          <option value="IL">Illinois</option>
          <option value="IN">Indiana</option>
          <option value="IA">Iowa</option>
          <option value="KS">Kansas</option>
          <option value="KY">Kentucky</option>
          <option value="LA">Louisiana</option>
          <option value="ME">Maine</option>
          <option value="MD">Maryland</option>
          <option value="MA">Massachusetts</option>
          <option value="MI">Michigan</option>
          <option value="MN">Minnesota</option>
          <option value="MS">Mississippi</option>
          <option value="MO">Missouri</option>
          <option value="MT">Montana</option>
          <option value="NE">Nebraska</option>
          <option value="NV">Nevada</option>
          <option value="NH">New Hampshire</option>
          <option value="NJ">New Jersey</option>
          <option value="NM">New Mexico</option>
          <option value="NY">New York</option>
          <option value="NC">North Carolina</option>
          <option value="ND">North Dakota</option>
          <option value="MP">Northern Mariana Islands</option>
          <option value="OH">Ohio</option>
          <option value="OK">Oklahoma</option>
          <option value="OR">Oregon</option>
          <option value="PA">Pennsylvania</option>
          <option value="PR">Puerto Rico</option>
          <option value="RI">Rhode Island</option>
          <option value="SC">South Carolina</option>
          <option value="SD">South Dakota</option>
          <option value="TN">Tennessee</option>
          <option value="TX">Texas</option>
          <option value="UM">United States Minor Outlying Islands</option>
          <option value="UT">Utah</option>
          <option value="VT">Vermont</option>
          <option value="VI">Virgin Islands</option>
          <option value="VA">Virginia</option>
          <option value="WA">Washington</option>
          <option value="WV">West Virginia</option>
          <option value="WI">Wisconsin</option>
          <option value="WY">Wyoming</option>
        </select></div>
      </div>
      <div class="sm-col sm-col-4 px1">
        <div class="mb3 tel required profile_zipcode">
          <label class="bold tel required" for="profile_zipcode"><abbr title="required" class="red display-none">*</abbr>
            <%= t('in_person_proofing.forms.zip_code') %>
          </label>
          <input class="block col-12 field string tel required zipcode" required="required" aria-required="true" pattern="(\d{5}([\-]\d{4})?)" type="tel" name="doc_auth[zipcode]" id="profile_zipcode"/>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="mt3">
    <button class="btn btn-primary btn-wide sm-col-6 col-12" type="submit">Continue</button>
  </div>
<% end %>

<%= render 'idv/cac/start_over_or_cancel' %>

app/views/idv/cac/present_cac.html.erb
<%= simple_form_for(:cac, url: url_for, method: 'PUT',
                    html: { autocomplete: 'off', method: :put, role: 'form' }) do |f| %>

  <h5 class="my1 caps bold accent-blue"><%= t('cac_proofing.step', step: 1) %></h5>
    <h1 class="h3 my0"><%= t('cac_proofing.headings.present_cac') %></h1>
    <div class="no-spinner">
      <p class="mt-tiny mb3">
        <%= t('cac_proofing.info.present_cac') %></p>
    </div>


  <div>
    <%= link_to t('forms.buttons.cac'), redirect_to_piv_cac_service_url, class:"btn btn-primary" %>
  </div>
<% end %>

<%= render 'idv/cac/start_over_or_cancel' %>

app/views/idv/cac/welcome.html.slim
h1.h3.my0 = t('cac_proofing.headings.welcome')
p.mt-tiny.mb3 = t('cac_proofing.info.welcome')
h1.h3.mb2 = t('cac_proofing.instructions.welcome')
ul.list-reset
  li.pt2.pb1
    .inline-block.mr2.mt1.align-top.circle.circle-number.bg-blue.white
      | 1
    .mr1.inline-block
      .h1.inline-block.bold = t('cac_proofing.instructions.bullet1')
      br
      = t('cac_proofing.instructions.text1')
  li.pt2.pb1
    .inline-block.mr2.mt1.align-top.circle.circle-number.bg-blue.white
      | 2
    .mr1.inline-block
      .h1.inline-block.bold = t('cac_proofing.instructions.bullet2')
      br
      = t('cac_proofing.instructions.text2')
  li.pt2.pb1
    .inline-block.mr2.mt1.align-top.circle.circle-number.bg-blue.white
      | 3
    .mr1.inline-block
      .h1.inline-block.bold = t('cac_proofing.instructions.bullet3')
      br
      = t('cac_proofing.instructions.text3')
  li.pt2.pb1
    .inline-block.mr2.mt1.align-top.circle.circle-number.bg-blue.white
      | 4
    .mr1.inline-block
      .h1.inline-block.bold = t('cac_proofing.instructions.bullet4')
      br
      = t('cac_proofing.instructions.text4')
  li.pt2.pb1
    .inline-block.mr2.mt1.align-top.circle.circle-number.bg-blue.white
      | 5
    .mr1.inline-block
      .h1.inline-block.bold = t('cac_proofing.instructions.bullet5')
      br
      = t('cac_proofing.instructions.text5')
= simple_form_for(:cac, url: url_for, method: 'PUT',
        html: { autocomplete: 'off', role: 'form', class: 'mt2' }) do
  br
  .mt0
    button type='submit' class='btn btn-primary btn-wide sm-col-6 col-6'
      = t('cac_proofing.buttons.get_started')
br

.mt2.pt1.border-top
- if user_fully_authenticated?
  = link_to cancel_link_text, account_path, class: 'h5'
- else
  = link_to t('two_factor_authentication.choose_another_option'), two_factor_options_path

== javascript_pack_tag 'clipboard'